# Generated by Django 3.2.16 on 2023-02-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMapp', '0002_alter_subscriptions__from'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subScriptions',
            new_name='Subscription',
        ),
        migrations.AlterField(
            model_name='gymusers',
            name='regNum',
            field=models.CharField(max_length=45),
        ),
    ]
