# Generated by Django 4.1.5 on 2023-02-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GYMapp', '0003_auto_20230201_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymusers',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('employment_id', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='GYMapp.gymusers')),
            ],
        ),
    ]
