# Generated by Django 3.2.16 on 2023-02-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYMapp', '0006_employee_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='_from',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='_to',
            new_name='to_date',
        ),
    ]
